### ISSUE TITLE
Have a left right button so users could view more pictures

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#10]
![image](https://user-images.githubusercontent.com/19883954/96750011-5ce22c00-1380-11eb-83ba-229b5519e035.png)

May want to look at the docs to see how it is structured 

[docs](https://www.petfinder.com/developers/v2/docs/l)

**Comment by Wei-J-Huang** [comment]
Hi, I would like to try to fix this issue :)
