### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#105]
Update readme so beginners or newcomers clone project,  set up a working environment, tips for new contributors, navigating through the project, links to bootstrap and react-bootstrap, mention each page has their own folder and anything you can think of

**Comment by redxzeta** [comment]
@yashguptaji are you still working on this?

**Comment by yashguptaji** [comment]
no, sorry I had no internet for 2 days, please remove me from this
thanks
