### ISSUE TITLE
Featured Pets in Home Page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#11]
![image](https://user-images.githubusercontent.com/19883954/96751876-96b43200-1382-11eb-8af5-3013e79ef016.png)

Featured Pets of the Day/Week either in a Card or Gallery

Clicking on the image takes u to the pet and hovering shows more images

Feel free to remove the animation in `home.css` 

Any more ideas are welcome

**Comment by samin-batra** [comment]
Hi @redxzeta can you assign this issue to me?

**Comment by redxzeta** [comment]
alright
