### ISSUE TITLE
Adding Pagination of the list of pets

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#12]
Currently displays one page of pets 

using this link         `https://api.petfinder.com/v2/animals?type=${type}&location=${zipCode}&limit=10&page=1`, in `PetType.js`

implement a next and previous button in `PetType.js` to view the next page of pets

**Comment by salihsenturk** [comment]
Hi,

I created a pull request for this issue.

**Comment by redxzeta** [comment]
issue with the deployed version on netlify

**Comment by salihsenturk** [comment]
What is the issue?

**Comment by redxzeta** [comment]
I think it might have to do with the dependency issue for findpets function in the use Effect. It works locally just not live

**Comment by salihsenturk** [comment]
Do you any detailed errors so I can investigate? I did not add any new dependencies.

**Comment by redxzeta** [comment]
![image](https://user-images.githubusercontent.com/19883954/97749765-db3f7c00-1aac-11eb-9b8e-59781964dc4b.png)
maybe it had to deal with this? 

Netlify:
![image](https://user-images.githubusercontent.com/19883954/97749867-032edf80-1aad-11eb-8fa7-7200a93d7d2c.png)

**Comment by salihsenturk** [comment]
Sorry about that. It was a warning on local. Now I wrapped findPets method in useCallback, the warning is gone and it seems working fine now.

Sent you a new pull request for this change.
