### ISSUE TITLE
Update Readme for beginners

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#125]
Instructions on installing yarn and differences between yarn and using npm

setting up the environment

How to fork the repo and make a pull request, contribute

links to bootstrap 5 and react bootstrap, react router 

Brief description of the folder structure each page has their own folder in components

setting up prettier in vscode and auto format on save

**Comment by iamhardikat11** [comment]
Hey, @redxzeta I am good at documentation can I too contribute for this issue. I am  Sophomore looking for Open Source Work.

**Comment by iamhardikat11** [comment]
Started but not finished.

**Comment by redxzeta** [comment]
@iamhardikat11 take your time
