### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#127]
# Planning to add supabase to the site

## Login Page

Create a sign in page could be similar to `Register.jsx`

put it in the accounts folder

*feel free to update `Register.jsx` styling too

Fields are Email and password

use `useForm` hook  for onChange, value in the inputfields look at `Register.jsx`

## App.js

Add a Route in App.js `/login` 

## Navbar

In the Navbar, add a nav drop down called Profile with links to `/login` and `/register`

##  Pull Request

Make a pull request to `add_supabase`

**Comment by rajdama** [comment]
I can do it.

**Comment by nguyenhung15913** [comment]
Hi, I am interested in this issue, could you please assign it to me thanks.
