### ISSUE TITLE
Feature suggestion - Geolocation

### ISSUE THREAD

**Issue by Seagullible** [redxzeta/Awesome-Adoption#132]
If we added geolocation, we could give the user's zip code to the Petfinder API call right away. That way, the animals that show up on the home page would be results from the user's zip code, instead of the default 19019. 

It would be best to do some research and find the least intrusive geolocation library for this, as we would just need the zip code.
We might be able to do this with the built-in React geolocation, which provides latitutde/longitude. In that case this would be a straightforward change.

**Comment by redxzeta** [comment]
yea looks like you could do lat and longitude 

![image](https://user-images.githubusercontent.com/19883954/137244596-d4bb03fd-6451-4146-8164-dd3d0f2a68f2.png)

**Comment by redxzeta** [comment]
yea
