### ISSUE TITLE
Create a Story Page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#145]
## Important

Switch branch to `add_supabase`

## Create files

create a folder in `components` called stories

in the folder create a file called `Stories.jsx`

You could also place your css files here

## Details 

The page consists of user stories with a link to read them

## First Section

Title would be User Stories

At the top, there would be a button filtering by location, date and then a link to add a story

## Second section

then there would be list of user stories 

![image](https://user-images.githubusercontent.com/19883954/137838964-6960469b-ebdb-4e9d-9b97-71b9be7356ac.png)

in this card, left side would be username + profile pic. You dont need to put the small circle

right side would be the title of the story, and then a button with a link to the full story

and then at the bottom would be the date created

I was thinking 2 or 3 stories per row but lets see how it looks first

## Pull Request

Make a pull request to the branch `add_supabase`

**Comment by redxzeta** [comment]
@suhhee1011 how are things going?

**Comment by suhhee1011** [comment]
Hi @redxzeta, I am still working on it :)
