### ISSUE TITLE
Adding a footer at the bottom of the page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#15]

**Comment by 2022akande** [comment]
I'd like to give it a shot

**Comment by redxzeta** [comment]
sure

**Comment by 2022akande** [comment]
I got as far as cloning the directory and creating a new branch but I'm not sure what to do afterwards. I opened the index file in vscode but I'm not sure if there is where the footer should be.

**Comment by redxzeta** [comment]
there isnt a footer yet.
u could make a component and place it at the bottom of the container
```
 <Container className="pawhub">
          <Switch>
            {" "}
            <Route path="/animal/:id">
              {token && <PetInfo token={token} />}
            </Route>
            <Route path="/pets/:type">
              {token && <PetType token={token} />}
            </Route>
            <Route path="/pets">{token && <Pets token={token} />}</Route>
            <Route path="/">
              <Home />
            </Route>
          </Switch>
// insert footer here  <Footer/>
        </Container>
// or here
```
And then u could create the `Footer.js`  in the folder `layout` if u want or its separate folder
and maybe add links in to the footer and (c) redxzeta 2020
[react bootstrap docs ](https://react-bootstrap.github.io/)
