### ISSUE TITLE
Add a button to allow user to search by their lat lng

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#154]
## In `PetType.js`

- [ ] clicking on a button allows the user to search based on lat long
- [ ] Remove the zip code line 
![image](https://user-images.githubusercontent.com/19883954/138005142-fd6dc960-efd7-4f66-9d2f-beb002d306f5.png)

- [ ] Make sure its mobile responsive

**Comment by Toshiuk** [comment]
I did these changes, but I was not sure if I should have removed the default behaviour to search by location, to just happen when the button is clicked.
