### ISSUE TITLE
Apply new card design to PetType.js

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#166]
- [ ] Apply new design from `Home.js` to `PetType.js`
- [ ] Make it reusable and create a file called `PetCard.jsx` in the `layout` folder and pass in props
- [ ] The placeholder img looks cramped in the new card design
- [ ] may have to adjust the css

![image](https://user-images.githubusercontent.com/19883954/138147591-0a927c3e-d3df-4862-81ed-9ee1d65ba990.png)

**Comment by rupalisingh** [comment]
Hi @redxzeta,

can you please assign this issue to me?
