### ISSUE TITLE
Add About Page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#17]
Create an About page and put a link in the nav bar
Just put in lorem ipsum filler text and a filler image.

**Comment by rdhaundiyal-indeed** [comment]
Please feel free to assign this to me. Thanks.

**Comment by rdhaundiyal-indeed** [comment]
Please feel free to assign me if nobody is working on this.

**Comment by rdhaundiyal-indeed** [comment]
Hi @redxzeta - I have added a PR. Please take a look.

PS: did not add any tests (I did not find tests for other components). If you add sample tests for Home component, I can follow the convention and add tests for About component. Thanks.

**Comment by redxzeta** [comment]
Im kinda unsure how to add tests.
