### ISSUE TITLE
Add a Modal Donate Form for Donate

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#174]
switch branch to `paw_dev`

- [x] Add a Modal Form so users can submit an org
- [x] A button to open the modal form
- [x] fields should be based from the `charities.json`
- [x] Validation that all the fields are filled out, `founded` is number,
- [x] show errors if invalid or empty
- [x] Make a pull request to `paw_dev`

**Comment by khush021** [comment]
Can I take this?

**Comment by AkshayHere** [comment]
Is this still open? 
I would like to contribute to this one

**Comment by redxzeta** [comment]
> Is this still open? I would like to contribute to this one

lmk if you have any questions or join discord if you need any help

**Comment by AkshayHere** [comment]
> 
> 
> > Is this still open? I would like to contribute to this one
> 
> lmk if you have any questions or join discord if you need any help

Sure :)
