### ISSUE TITLE
Fix Pet Page with no images

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#19]
Some of the Pets do not have images and and viewing their page bugs it out

**Comment by Denpex** [comment]
Hi @redxzeta I would love to do this task also I want to implement a simple gallery for the Pet page and fix the nav bar height when the image is loaded inside of the Pet page.

Tasks: 
- [ ]  Fix pet page with no images
- [ ]  Add gallery to pet page 
- [ ]  Fix nav bar height when images are loaded in pet page

**Comment by redxzeta** [comment]
Sounds great go for it

**Comment by Denpex** [comment]
I have created a new pull request, hope you like it
