### ISSUE TITLE
improve ui of resources page

### ISSUE THREAD

**Issue by akshay399** [redxzeta/Awesome-Adoption#204]

**Comment by redxzeta** [comment]
What suggestions do you have?

**Comment by akshay399** [comment]
> What suggestions do you have?

put those headings in different sections like a box and add margins on suitable places

![image](https://user-images.githubusercontent.com/55823965/139490879-34a99541-4551-45d4-8f65-13cd982a164c.png)

**Comment by redxzeta** [comment]
> > What suggestions do you have?
> 
> put those headings in different sections like a box and add margins on suitable places
> 
> ![image](https://user-images.githubusercontent.com/55823965/139490879-34a99541-4551-45d4-8f65-13cd982a164c.png)

oh i see. did you want to work on it?

**Comment by akshay399** [comment]
yes i do, please assign it to me

**Comment by akshay399** [comment]
hi @redxzeta i made a [PR](https://github.com/redxzeta/Awesome-Adoption/pull/206) please review it and suggest changes if any, also will this pr be included in hacktoberfest? asking because you didnt mention the tag here.
