### ISSUE TITLE
small UI improvements

### ISSUE THREAD

**Issue by dev-abir** [redxzeta/Awesome-Adoption#205]
I think it would be better to put "Pawternity Hub" on the navbar itself in the home page.
Another issue, the dogs in the animation near the bottom of the homepage looks like they are elongated....... Is an animation necessary..?
Then, the images are without any frame... Maybe we can add shadows, make them rectangular (or round rectangle) instead of oval.
These small changes will probably make the website more appealing and professional.
I may work on these issues, first let me know your views...

**Comment by redxzeta** [comment]
Yea it could sure use those improvements. Can u post screenshots of the pages that needs work?

**Comment by dev-abir** [comment]
I just did one small change... simple though, see whether you like it or not.
I am having some problems regarding generation of the API key, it would be nice if you could help me out, so that I could proceed with the rest of the changes.

**Comment by redxzeta** [comment]
> I just did one small change... simple though, see whether you like it or not. I am having some problems regarding generation of the API key, it would be nice if you could help me out, so that I could proceed with the rest of the changes.

Join the discord so I can send u the api key
