### ISSUE TITLE
Add a modal to profile

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#207]
Switch branch to `add_profile`

- [ ] add a button on Profile that opens up a modal
- [ ] users should be able to change username, description
- [ ] add validation username should not be blank
- [ ] add a button that submits the update
- [ ] add a button to cancel and show a warning

**Comment by dhillonks** [comment]
Can I work on this?

**Comment by dhillonks** [comment]
@redxzeta Created a pull request, Please take a look: https://github.com/redxzeta/Awesome-Adoption/pull/210
