### ISSUE TITLE
PetInfo Testing help

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#208]
Running into some issues in `petinfotest.js`

Trying to test the data in PetInfo to see if it comes up by mocking the request but it gets stuck on the spinner

Switch branch to `paw_tests`  to check it out

**Comment by rclee91** [comment]
Hello, just letting you know that `paw_tests` branch doesn't exist. 
So, I'm wondering if you'd like someone to create tests for `petInfo.js`, or if this is a closed issue. Thanks!

**Comment by redxzeta** [comment]
Yea creating tests for `petInfo`

**Comment by redxzeta** [comment]
Just make a branch based off on `paw-dev`

**Comment by rclee91** [comment]
In that case, could you assign this to me please?
