### ISSUE TITLE
image size is not consistent, in pet info page

### ISSUE THREAD

**Issue by dev-abir** [redxzeta/Awesome-Adoption#213]
The image size of the pets' image in the slider, at the top of pet info page is not consistent.
Moreover, the images doesn't change on sliding, in mobile, and there is no button for going to the next/previous image.
Currently, after viewing one image, the user have to scroll down, then click on another image.
This could be improved, and bootstrap has a gallery/image slider component, so we can use that as well.

**Comment by redxzeta** [comment]
oh yea thats a good idea

**Comment by drew5494** [comment]
Hi can I work on this?
