### ISSUE TITLE
register and login unit testing

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#222]
To expand the test coverage, we should test login and register components.

## Description
Add tests for the following components:

- src/components/SLogin
- src/components/Register

Use `src/testServer.js` to mock server requests. Follow `about.test.js` as a reference if needed:
https://github.com/redxzeta/Awesome-Adoption/blob/main/src/components/about/__tests__/about.test.js
https://github.com/redxzeta/Awesome-Adoption/blob/main/src/testServer.js

**Comment by dhillonks** [comment]
@redxzeta Can I work on this?
