### ISSUE TITLE
Restructuring the fetching pet api token

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#227]
Would like some suggestions because there have been issues fetching the pet api for the token as null

@rclee91 

> Some of the code in petInfo.js originally kept breaking the app, especially when refreshing the page. The problem was some objects returned null. So I added conditions for them. The issue I think is usePetAuth() for tokenHeaders is async, and it also affects useFetch(), so sometimes not all the data have been loaded when the html elements are rendering.

**Comment by rclee91** [comment]
I can try and have a poke at this. It was bothering me as well when I was writing tests for petInfo :D

**Comment by redxzeta** [comment]
> I can try and have a poke at this. It was bothering me as well when I was writing tests for petInfo :D

how are things going?

**Comment by rclee91** [comment]
Hey sorry, I've been a bit busy last week. 
But I've been trying to do some research on this. 

Basically, I added some basic console logs in `Pet Info` to see what comes out.
![image](https://user-images.githubusercontent.com/32626950/144122674-e46c1d30-4f0b-404d-b1ab-8595107f2ad9.png)

and this is what I get from a single page load.
![image](https://user-images.githubusercontent.com/32626950/144122782-d4cf9a32-8248-426e-b558-43482d03195a.png)

So I'm sticking to my original theory of the sync states. So I'm trying to look for a solution for it right now (any thoughts? :D). 

But in the case that I'm wrong, it might also have something to do with how `useFetch()` and `usePetAuth()` is written.
So, if its ok with you, I'd like to reserve doing unit tests for these two components, just to make sure they're acting the way we want them to.

**Comment by redxzeta** [comment]
> Hey sorry, I've been a bit busy last week. But I've been trying to do some research on this.
> 
> Basically, I added some basic console logs in `Pet Info` to see what comes out. ![image](https://user-images.githubusercontent.com/32626950/144122674-e46c1d30-4f0b-404d-b1ab-8595107f2ad9.png)
> 
> and this is what I get from a single page load. ![image](https://user-images.githubusercontent.com/32626950/144122782-d4cf9a32-8248-426e-b558-43482d03195a.png)
> 
> So I'm sticking to my original theory of the sync states. So I'm trying to look for a solution for it right now (any thoughts? :D).
> 
> But in the case that I'm wrong, it might also have something to do with how `useFetch()` in `useHooks/useFetch` and `usePetAuth()` in `context/TokenContext` is written. So, if its ok with you, I'd like to reserve doing unit tests for these two components, just to make sure they're acting the way we want them to.

yea thats fine. I was checking out [swr](https://swr.vercel.app/)  and [react-query](https://react-query.tanstack.com/) to replace the useFetch custom hook since it caused some problems i think.

**Comment by rclee91** [comment]
Oh neat.
I think its a good idea to use available working tools instead of coming up with custom ones. 
Do you have a personal preference which of the two to use?

**Comment by rclee91** [comment]
Ok, I'll try restructuring with swr
