### ISSUE TITLE
create modal form for user story

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#232]
create a branch based on `paw-dev` and create pr to `paw-dev` when done

- [ ] create a modal form for user story
- [ ] fields should have title, description, location
- [ ] check that the fields are not empty 
- [ ] post valid story to the table `stories` using [react-supabase](https://react-supabase.vercel.app/documentation/data/use-insert)
- [ ] display any errors for the user
- [ ] use a spinner when posting the data you could use `FetchingButton.jsx` in `layout` 
- [ ] success should close the modal 
- [ ] have the option to reset fields
- [ ] be sure to clear the fields after closing the modal 
- [ ] if you have time, write some tests 

you could use `useForm` for the fields 
open to suggestions also

**Comment by hlavu** [comment]
Hi @redxzeta, I’d like to work on this issue. Please it to me.

**Comment by redxzeta** [comment]
> Hi @redxzeta, I’d like to work on this issue. Please assign it to me.

let me know if you need help setting up the environment

**Comment by hlavu** [comment]
Yes sure. Thank you.

**Comment by hlavu** [comment]
Hi @redxzeta, here is the form I just created. Please take a look to see: does this design have anything you want to change or it is fine.

![image](https://user-images.githubusercontent.com/44437742/144321997-df25a782-b936-4a9a-b72b-03221affb130.png)

**Comment by redxzeta** [comment]
yea that looks fine. you could remove address and postal code and put Location.

If you know a way that lists the countries/cities, you could put a dropdown for it
