### ISSUE TITLE
Refactoring storyCleaner and nameCleaner

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#239]
- [ ] Get all the functions and put it in a folder called `utilsCleaner` in `utils`. File name should be `index.js`
- [ ] Make all the functions `export const ....`
- [ ] Fix any of the affected files that uses them
- [ ] Fix `nameCleaner` so it's compatible previous versions of node ie node 14.x; for example 
To something like `.replace(/&#039;/gim, "'")`

**Comment by trujillo9616** [comment]
Hey I could also work this issue! Just to corroborate, the fix for `nameCleaner` should be implementing a regex search? I looked up what /gim meant and I found out that they are Regex modifiers g(lobal) i(nsensitive) m(ulti-line). I am correct in this assumption? 😅

**Comment by redxzeta** [comment]
> Hey I could also work this issue! Just to corroborate, the fix for `nameCleaner` should be implementing a regex search? I looked up what /gim meant and I found out that they are Regex modifiers g(lobal) i(nsensitive) m(ulti-line). I am correct in this assumption? 😅

yea id assume so
