### ISSUE TITLE
Displaying User Stories

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#253]
display the user stories from supabase

![image](https://user-images.githubusercontent.com/19883954/145485926-24c1043e-9e59-41d9-a800-60f466e95a8e.png)

- [ ] Left side of the card from top to bottom: User profile pic, username, country (but if you can make room, include the region)
- [ ] right side of the card: title of the story
- [ ] use react-supabase to fetch user stories and name of table `stories`
- [ ] fetching 6 recent stories first 
- [ ]  left and right arrows to view more stories
- [ ] show an error if something went wrong
- [ ] use the placeholder from `react-bootstrap` to show that it is loading

## References
[supabase fetch](https://supabase.com/docs/reference/javascript/select)
[react-supabase select](https://react-supabase.vercel.app/documentation/data/use-select)
[relationships supabase](https://www.kronic.dev/blog/supabase-relationships)

**Comment by amm98d** [comment]
Hi, I would like to take this, if possible :)

**Comment by amm98d** [comment]
Hey @redxzeta, can you help me set up the environment. I got a Petfinder API, however, the .env also needs a supabase url, can you tell me where I can get that?

**Comment by redxzeta** [comment]
> Hey @redxzeta, can you help me set up the environment. I got a Petfinder API, however, the .env also needs a supabase url, can you tell me where I can get that?

It's in my discord. Link is in the Readme

**Comment by redxzeta** [comment]
@amm98d are you working on this still ?
