### ISSUE TITLE
Create a page for tips for adopting pets

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#254]
create a branch based off on `paw-dev`

- [ ] Create a page for `/tips`
- [ ] Add some tips, tricks, and preparation for adopting a pet
- [ ] add some links resources that opens in a new tab
- [ ] in the nav bar create a drop down at resources and put the link to the page there

**Comment by amm98d** [comment]
Hi, I would like to take this, if available :)

**Comment by Pongy-jr** [comment]
Hi could you assign this to me, I would like to work on this.
