### ISSUE TITLE
Add one random pet in Pets.js

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#256]
- [ ] Use this url to fetch one random pet `https://api.petfinder.com/v2/animals?limit=1&sort=random`
- [ ] use `useSWR` to fetch it along with the fetcher. Example in `PetInfo.js` 
- [ ] When it is fetching, use a placeholder like a spinner from `react-bootstrap`
- [ ] If it errors, show an error message
- [ ] use `AnimalType` to show some info on the pet. 
- [ ] type would be name of pet, 
- [ ]  if no img use the `placeholder.jpg`
- [ ] the link would be to the PetInfo page
- [ ] fix some of the tests
- [ ] use msw to mock the api

**Comment by munnawng** [comment]
I'd like to be assigned to this as my first issue!
