### ISSUE TITLE
wait until all the images are done loading in About page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#258]
![image](https://user-images.githubusercontent.com/19883954/145724284-646dca23-bbd3-4959-a799-d4ac0b226211.png)

Wondering if its possible to wait  until all the contributors imgs are fully loaded. Atm, it will show orange dots until the image loads

**Comment by iswarmondal** [comment]
I can implement a `view more` or `scroll to reveal/load` feature in this section.
Please assign the issue to me.

**Comment by iswarmondal** [comment]
Thanks for assigning it to me.

**Comment by redxzeta** [comment]
@iswarmondal are you working on this still?
