### ISSUE TITLE
Add A resource page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#26]
Info for adopting pets

Info about covid 

Helpful links and styling the page if u can

**Comment by izanf** [comment]
Can you explain more about this issue? Please.

**Comment by redxzeta** [comment]
More information or links on adopting pets, covid,

**Comment by MLJBrackett** [comment]
Hey @redxzeta Could you assign this issue to me or is it already taken?

**Comment by redxzeta** [comment]
sure
