### ISSUE TITLE
Refactoring PetType

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#262]
- [ ] use SWR to fetch the api. you can look at `PetInfo.js` as an example
- [ ] Show an error message along with an image that something went wrong [pexel](https://www.pexels.com/) or there are no pets around the area
- [ ] remove any `console.logs`
- [ ]  add some tests and use msw to mock the api

**Comment by trujillo9616** [comment]
Hey! I would like to give this issue a try 😁. Could you assign it to me?
