### ISSUE TITLE
Improve the homepage layout

### ISSUE THREAD

**Issue by iswarmondal** [redxzeta/Awesome-Adoption#271]
### Here are my suggestions on improving the layout of the home page.

- Have a hero section instead of a cute dog's image at the beginning
- Add a `call to action` button in the hero section
- After that give a brief description about `What we do?`
- Add some random organization after the `Featured Pets` section under the heading of `Donate`

#### I think these features will make the home page more standard and appealing to the end-user

**Comment by iswarmondal** [comment]
I would be very happy to work on it if I was given a chance.

**Comment by redxzeta** [comment]
That's a good idea

There's a pr that's going to affect the home page just to be aware

#261

**Comment by iswarmondal** [comment]
Hay @redxzeta I did a PR take a look at that and let me know.
