### ISSUE TITLE
Create 'favorites' section

### ISSUE THREAD

**Issue by Zeusjonass** [redxzeta/Awesome-Adoption#273]
I think we could create a section in the application where a list of pets that the user has been marking while browsing is displayed.

We could add a button to the pet's view so that it's added to the 'favorites' section and then be able to consult the list thanks to a button in the navbar.
Something like:
<img width="1406" alt="Screen Shot 2022-01-04 at 10 13 02" src="https://user-images.githubusercontent.com/35499170/148081030-26e38489-e2e4-40c2-b7ef-a6e1b8fe49ba.png">

For this, we could use localstorage.

Let me know what you think about the idea :)

**Comment by Zeusjonass** [comment]
Let me know if you want me to develop the issue :)

**Comment by redxzeta** [comment]
Oh yea I was thinking some like that. Seems like a great idea.

**Comment by redxzeta** [comment]
I could create a table on supabase. Let me know the fields you would need

**Comment by Zeusjonass** [comment]
I was thinking we could use localstorage for favorites list, I found a tutorial (it uses ts, I'd have to pass it to js): https://medium.com/wesionary-team/creating-favorites-list-using-localstorage-in-react-part-ii-5f2766369c4f. You think it'd be a better option to create a table on supabase to store the list of favorites per user?

**Comment by redxzeta** [comment]
was thinking of storing favorites somewhere 

we could do local storage for now
