### ISSUE TITLE
Confused with restart app instructions

### ISSUE THREAD

**Issue by briandgomez** [redxzeta/Awesome-Adoption#296]
## I am getting this error when starting the application:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/69539559/155255695-e4b5ba32-12b3-4414-aaeb-3ee8486a1942.png">

I followed all the steps from the 'Pet Finder Developer API Key' section in the readme and got this error when typing 'yarn start'. 
I currently have this in the .env file:
`REACT_APP_PETFINDER_KEY = APIKEYhere&client_secret=secretkeyhere` (with my API key and secret key substituted) and 
`grant_type=client_credentials&client_id=${process.env.REACT_APP_PETFINDER_KEY}` (exactly as its shown here)

Can I get some clarification as to what to do with: `grant_type=client_credentials&client_id=${process.env.REACT_APP_PETFINDER_KEY}`?

(I am also just starting to work on open source)

**Comment by redxzeta** [comment]
oh hey @briandgomez 

looks like you're missing the supabase keys which are in the discord
the link to the discord is in my readme

**Comment by briandgomez** [comment]
@redxzeta Just joined the discord. I think I found it. Thanks.
