### ISSUE TITLE
Open to Suggestions on improving the site

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#3]
The site could use some more improvements so feel free to open a PR for anything that you think is an improvement or any issues that come up.
The goal is to make the website to have access to information on the pets to adopt.

The site could be accessed here: http://pawternityhub.tech/

**Comment by dennismoha** [comment]
I ran the website through google lighthouse and found some issues but these are some I  felt would be necessary to solve so far.
1) Set an explicit width and height on image elements to reduce layout shifts and improve CLS
2) Some Images in the card section do not have an alt attribute

**Comment by redxzeta** [comment]
interesting. I'll add it to the issues

**Comment by Fpj-11** [comment]
A suggestion I would like to give. Can try for different font.

**Comment by redxzeta** [comment]
what kind of font u suggest?

**Comment by Fpj-11** [comment]
https://fonts.google.com/share?selection.family=Crimson%20Text:ital@1
This one maybe

**Comment by redxzeta** [comment]
alright did you want to try it out?

**Comment by Fpj-11** [comment]
Yes I'll try

**Comment by Fpj-11** [comment]
Yes, I will try it out. 
I have forked this project but how do i run it on my local machine?

**Comment by redxzeta** [comment]
There's instructions on the Readme
