### ISSUE TITLE
Pet Card gets extended if the Breed is long

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#31]
Some Pets have multiple breeds and it creates a new line extending the height of the card.

**Comment by yighax** [comment]
hi, i would give it a try

**Comment by izanf** [comment]
If possible, create with an image of example from the issue.

**Comment by redxzeta** [comment]
![image](https://user-images.githubusercontent.com/19883954/97651813-49872e80-1a1a-11eb-96ed-b4f8183d294b.png)
also depends on the screen size such as 1024px

**Comment by izanf** [comment]
Hmm, all right. I think on two possible ways:
1 - Transform this page on mosaic (I don't believe that this way is better, for the complexity)
2 - Use Grid Layout to define a height pattern for all cards to each line. For example, the second cards will assumes the height size from the other cards.
Do you have any idea about that?

**Comment by redxzeta** [comment]
Maybe I'll just add a fixed height with media queries
