### ISSUE TITLE
Filter method for User Favorited Pets

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#310]
Add a filter method to filter the user favorited pets by type (dog, cat, bird, rabbit, horse) and reset filter

**Comment by prasadasabe22** [comment]
Hi @redxzeta also can I work on this? Love to contribute in this regards.

**Comment by redxzeta** [comment]
> Hi @redxzeta also can I work on this? Love to contribute in this regards.

sure
