### ISSUE TITLE
Redesign Login and Register page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#311]
Current page looks plain. Feel free to redesign the page would prefer to keep the same color theme

**Comment by redxzeta** [comment]
I should mention to also implement loading , error, and success state ( I think only for register. Login redirects to home)

**Comment by VishSeen** [comment]
Yoo @JayChavan-23 , yes I'll be implementing this feature.

**Comment by redxzeta** [comment]
@VishSeen how are things going?

**Comment by VishSeen** [comment]
Yes implementation in progress. Should be good in a few days.

**Comment by redxzeta** [comment]
> Yes implementation in progress. Should be good in a few days.

Alright thanks for the update. No rush

**Comment by VishSeen** [comment]
@redxzeta Redesign done. I can't push or PR here. Getting access denied, Can you check ?

**Comment by redxzeta** [comment]
> @redxzeta Redesign done. I can't push or PR here. Getting access denied, Can you check ?

OH did u fork it?

**Comment by VishSeen** [comment]
I cloned it and worked on a new branch

**Comment by redxzeta** [comment]
Ahh I'll invite u then

**Comment by VishSeen** [comment]
Any idea why i'm getting an erro ?? 

![image](https://user-images.githubusercontent.com/13452864/173170465-7f09535a-94ff-4d24-ada2-edb2b93fdd78.png)

**Comment by redxzeta** [comment]
Hmmm might be cuz of the tests

**Comment by redxzeta** [comment]
Could do git push  --no-verify

**Comment by VishSeen** [comment]
> Could do git push  --no-verify
> 
> 
> 
> 

It is indeed because of the tests.. i will try to fix it in a bit.
