### ISSUE TITLE
fix: bootstrap update 

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#315]
`(12:30806) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.`

**Comment by CodyMcCarty** [comment]
Hi.  First time trying to help with open source.  I fixed this one.  I'm looking into how to do a pull request

**Comment by redxzeta** [comment]
u can fork the repo
create a branch and add your changes
then create a pull request
