### ISSUE TITLE
Placeholder Image

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#32]
Maybe a more elegant placeholder image?

![image](https://user-images.githubusercontent.com/19883954/97603510-be7e4800-19c9-11eb-9192-68ea8d24de04.png)

**Comment by MLJBrackett** [comment]
Hey @redxzeta I'd love to take a shot at this, please assign me. Do you have any ideas for the placeholder or do I have complete freedom for now?

**Comment by redxzeta** [comment]
no ideas so up to you
