### ISSUE TITLE
ability to remove favorites from favorites page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#320]
Go to `Favorites.tsx`

add a button to remove favorited pets in the favorites page and updates the state. Check out `FavoriteSection.tsx` as an example

**Comment by redxzeta** [comment]
> Hi! Can I be assigned to this! This would be my first open source contribution and I love that it’s helping people find pets! :)

Sure :) 

if you need help u can go on discord also updated the issue to help u out

**Comment by bcastillo32** [comment]
just joined discord! pumped to be able to help here :D

**Comment by bcastillo32** [comment]
> 

Thanks! Just joined the discord. Pumped to be able to help :D

**Comment by redxzeta** [comment]
> > 
> 
> Thanks! Just joined the discord. Pumped to be able to help :D

just wondering if ur still working on this?

**Comment by bcastillo32** [comment]
hi! yes, I am. I was out last week and then on a work trip the week before that but I am definitely going to do it. I think I will be able to get it done this weekend! Sorry for the delay and for not keeping you updated. I will get this done.

**Comment by bcastillo32** [comment]
> 

hi! yes, I am. I was out last week and then on a work trip the week before that but I am definitely going to do it. I think I will be able to get it done this weekend! Sorry for the delay and for not keeping you updated. I will get this done.

**Comment by redxzeta** [comment]
> > 
> 
> hi! yes, I am. I was out last week and then on a work trip the week before that but I am definitely going to do it. I think I will be able to get it done this weekend! Sorry for the delay and for not keeping you updated. I will get this done.

Alright thanks for the update. No rush

**Comment by bcastillo32** [comment]
> 

no prob. thank you for the opportunity to help. Looking forward to helping more and more with this!
