### ISSUE TITLE
TypeScript Review

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#321]
I'm not the greatest at TypeScript so if anyone wants to code review or refactor any of the code

**Comment by p14** [comment]
I'd be more than happy to take a look this afternoon if you're still wanting an extra pair of eyes on it. I'm not an expert by any means, but I have been living inside of Typescript for the past few years surrounded by some brilliant people.

**Comment by redxzeta** [comment]
> I'd be more than happy to take a look this afternoon if you're still wanting an extra pair of eyes on it. I'm not an expert by any means, but I have been living inside of Typescript for the past few years surrounded by some brilliant people.

sure sounds good :)
