### ISSUE TITLE
feat: Search user profile

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#325]
- Create a new component to search users by username or show all users sort by date with pagination
- route should be `/profile`
- use supabase to search 
- Display the user profile cards (username, avatar_url, and a link to their profile)
- show error case `No profiles found`
- Loading profile card case

Let me know if u have design ideas for user profile cards

**Comment by danyalasif** [comment]
I tried working on this, have added a preview to the PR, let me know what you think
