### ISSUE TITLE
revamp Pets.tsx

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#326]
Current page images are not all the same size so it looks kinda funky. 

Could resize all the images, except the random pet, so they call all be the same

if anyone has any ideas to redesign `Pets.tsx` on the route `/pets`

post them here

**Comment by MuizU** [comment]
We can set a default width and height, then use `object-fit:scale-down;` to make sure the image is represented with the specified dimensions without being stretched.

**Comment by redxzeta** [comment]
did you want to try and tackle this?

**Comment by MuizU** [comment]
Sure

**Comment by redxzeta** [comment]
pet images would probably need to be replaced too

**Comment by MuizU** [comment]
Sure, that can be done as well. What would you suggest as the default dimensions for the pet images?

**Comment by redxzeta** [comment]
Hmm want to play around with it?

**Comment by MuizU** [comment]
Of course
