### ISSUE TITLE
Rename Donate page to Organizations

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#327]
Organizations seems to make more sense than Donate

rename the route, test and the page

see if there's an api to fetch organizations

**Comment by YaSh8202** [comment]
Hi @redxzeta , I would like to work on this issue. Please feel free to assign me.

**Comment by likileads** [comment]
Hi, Can I be assigned to this issue.

Also I wanted to see the application, so I cloned the repo and ran  `yarn` to install node-modules and started the server, but I could only see a white screen,  can you help me with this
![image](https://user-images.githubusercontent.com/70283754/174133769-f1477ed9-108a-4568-8f00-daec1c94c562.png)

**Comment by redxzeta** [comment]
1. may want to fork the repo first since u wont be able to push if u cloned 
2. make sure ur using node 16
3. There are env variables to set up with
4. https://github.com/redxzeta/Awesome-Adoption#pet-finder-developer-api-key
5. https://github.com/redxzeta/Awesome-Adoption#supabase
6. join the discord if u have more questions too :)

**Comment by likileads** [comment]
Please review my pull request: [343](https://github.com/redxzeta/Awesome-Adoption/pull/343)
