### ISSUE TITLE
Create Profile settings page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#328]
- [ ] Create `Settings.tsx`
- [ ] Only accessed by authenticated users. redirect unauthorized users to home page. you can use `PrivateRoute`
- [ ] on the route `settings`
- [ ] user can change username , description 
- [ ] use can `react-supabase` https://react-supabase.vercel.app/ or regular supabase to make requests to the table `profiles`

**Comment by MuizU** [comment]
@redxzeta can this be assigned to me? I can work on it.
