### ISSUE TITLE
Add Tool tip in about page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#349]
Add tooltip when hovering over contributors. Hover should display username

You can use [react-daisy-ui](https://react.daisyui.com/?path=/story/data-display-tooltip--default) or [daisy-ui](https://daisyui.com/components/tooltip/) or tailwind

![image](https://user-images.githubusercontent.com/19883954/184472243-316388e6-13c3-4fa6-a37b-f9c01d0b97a2.png)

**Comment by danyalasif** [comment]
Hey [redxzeta](https://github.com/redxzeta), I can take this task if it's available.

**Comment by redxzeta** [comment]
> Hey [redxzeta](https://github.com/redxzeta), I can take this task if it's available.

Sure 👍
