### ISSUE TITLE
Fix Resources Page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#350]
- Spread out buttons
- Button's in a new line not in the same line as the text
- add more spacing between the buttons and paragraphs
- update any information

**Comment by sunidhisachan** [comment]
I can work on this issue . @redxzeta Please assign this to me.

**Comment by prasadasabe22** [comment]
Hi @redxzeta is this issue still open? I would like to work on this issue and to make a contribution.

**Comment by Jovita2019** [comment]
I wanna give it a try

**Comment by prasadasabe22** [comment]
@redxzeta I pulled this project into my local repo. but it is showing lots of errors. Can you suggest something so that I will be able to run this project in my local machine?

**Comment by redxzeta** [comment]
> @redxzeta I pulled this project into my local repo. but it is showing lots of errors. Can you suggest something so that I will be able to run this project in my local machine?

Click on fork in the top right and then clone that repo

**Comment by prasadasabe22** [comment]
@redxzeta yes I did those steps (creating fork and then cloning that into my local repo). But after opening it in VS code it showing tons of error mainly cannot find module type errors. Image attached for reference. It would be helpful for if you can give some idea about it.
![image](https://user-images.githubusercontent.com/109573052/184546225-fe69ec05-ab1b-4e1a-bb57-f4e6594dc9ef.png)

**Comment by redxzeta** [comment]
> @redxzeta yes I did those steps (creating fork and then cloning that into my local repo). But after opening it in VS code it showing tons of error mainly cannot find module type errors. Image attached for reference. It would be helpful for if you can give some idea about it. ![image](https://user-images.githubusercontent.com/109573052/184546225-fe69ec05-ab1b-4e1a-bb57-f4e6594dc9ef.png)

oh i dont think u installed node modules?

run `yarn` in terminal to install the `node_modules` then run `yarn start`

**Comment by prasadasabe22** [comment]
hey @redxzeta above mentioned got resolved by using "npm install --save @types/react --force" command but now I am facing other errors as mentioned below. As it is taking much more time, Whether there is any other way to work with the source code. So as to run and check for modification. Please suggest.

![image](https://user-images.githubusercontent.com/109573052/184606764-272bcf58-e7b8-4fde-858e-5296c6486076.png)

**Comment by redxzeta** [comment]
> hey @redxzeta above mentioned got resolved by using "npm install --save @types/react --force" command but now I am facing other errors as mentioned below. As it is taking much more time, Whether there is any other way to work with the source code. So as to run and check for modification. Please suggest.
> 
> ![image](https://user-images.githubusercontent.com/109573052/184606764-272bcf58-e7b8-4fde-858e-5296c6486076.png)

I put the env keys in discord. 
I posted instructions on the Readme.
