### ISSUE TITLE
Fix Tips.tsx

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#359]
- [ ] Convert to use tailwind
- [ ] Remove `tips.css`
- [ ] `  <Button color="primary">Adopt</Button>` change to use Link from react-router-dom with `className='btn btn-primary'
- [ ] add a link in the footer

**Comment by danyalasif** [comment]
Hey redexzeta, I can work on this task, let me know if it's available.

**Comment by redxzeta** [comment]
> Hey redexzeta, I can work on this task, let me know if it's available.

Sure go for it
