### ISSUE TITLE
Align menu to right

### ISSUE THREAD

**Issue by izanf** [redxzeta/Awesome-Adoption#36]
If we divide navbar with "logo" to left and menu to right I believe that is a good improvement.

**Comment by redxzeta** [comment]
I see so the links would be on the right?

**Comment by Fpj-11** [comment]
I will try to work on this issue.

**Comment by Saisrinivenkat** [comment]
Assign me I complete this in 2 days

**Comment by Saisrinivenkat** [comment]
Doing this with lower version of react-bootstrap is kinda complex.

Updating react-bootstrap to version@1.6.0 solves this issue

Adding container and justifying menu in NavigationBar.js
![image](https://user-images.githubusercontent.com/55131291/119792154-198e0400-bef3-11eb-920d-b2a40363bc17.png)

Then Header will be like this
![image](https://user-images.githubusercontent.com/55131291/119792499-5e199f80-bef3-11eb-9463-7171cee3c8bf.png)
