### ISSUE TITLE
Refactor test files that use msw

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#370]
Deprecations
req.body is deprecated. Please use explicit request body reading methods: req.text(), req.json(), req.arrayBuffer() (other methods, like req.formData() are currently not supported).
```typescript
rest.post('/user', async (req, res, ctx) => {
  const newUser = await req.json()
})
```
req.body is still present for compatibility reasons but will be removed in the next releases.

**Comment by AlexJBlair** [comment]
I can take a look at this :D

**Comment by AlexJBlair** [comment]
Is this just asking to replace all req.body calls due to deprecation?

**Comment by redxzeta** [comment]
> Is this just asking to replace all req.body calls due to deprecation?

Yea haha

**Comment by AlexJBlair** [comment]
So I am not too familiar with promises. For some reason this snippet is expecting a promise to be returned if any of the new methods are used. 
`test("should display wrong password", async () => {
    server.use(
      rest.post("https://test.supabase.co/auth/v1/token", (req, res, ctx) => {
        const { password } = req.text();
        if (password !== "bones1234") {
          return res(
            ctx.status(401),
            ctx.json({
              message: "Wrong Password",
            })
          );`

**Comment by redxzeta** [comment]
> 

sorry for late reply i think u can just wrap it with async await 

```javascript
    server.use(
      rest.post(
        "https://test.supabase.co/auth/v1/token",
        async (req, res, ctx) => {
          const { password } = await req.json();
          if (password !== "bones1234") {
            return res(
              ctx.status(401),
              ctx.json({
                message: "Wrong Password",
              })
            );
          } else {
            return res(
              ctx.status(200),
              ctx.json({
                message: "Success",
              })
            );
          }
        }
      )
    );
```
