### ISSUE TITLE
Add a contact form

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#389]
- [ ] Create a contact form page using tailwind daisyui/react-daisyui
- [ ] 3 fields: name, email, message
- [ ] Add a link in the footer
- [ ] Be sure to add it in `App.tsx` on the route `contact`
- [ ] use react hook form along with  validations

**Comment by j0hannsenn** [comment]
Hey, I am new to open source and would like to make my first contribution. Did I understand correctly, that only the page with the forms are required for this issue and no further functions than the validations? If this is the case, can you assign this issue to me? I would like to start working on the tasks.

**Comment by redxzeta** [comment]
> I have tried to run the project but got the same error after 'yarn start' mentioned in this Issue #350 ('supabaseUrl is required'). So I am unassigning me from this issue due to lack of time. But thank you a lot for giving me a try!

Env keys are in discord

**Comment by mamba-dev-KE** [comment]
I can give this a go mate. Kindly assign it to me

**Comment by mamba-dev-KE** [comment]
@redxzeta is it a requirement to write unit tests?

**Comment by redxzeta** [comment]
> @redxzeta is it a requirement to write unit tests?

Optional. It will be great to have tests or could be a different issue

**Comment by mamba-dev-KE** [comment]
@redxzeta I did a PR for this...kindly do a code review as soon as you are able. Thanks.
