### ISSUE TITLE
Implement dark mode theme 

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#397]
- Use https://daisyui.com/theme-generator/ to create a dark theme 
- add a theme to the tailwind config https://daisyui.com/docs/config/
-  add an icon here
![image](https://user-images.githubusercontent.com/19883954/185951428-42a503ac-2180-41db-a600-2af9f4a2fcb0.png)

- use the sun moon icon from here to switch between the themes
- For now use local storage to store the theme unless there is a better suggestion

**Comment by JP-sDEV** [comment]
I'll take this issue up! Aiming to have it done by next week (Aug 29)

**Comment by redxzeta** [comment]
> I'll take this issue up! Aiming to have it done by next week (Aug 29)

Are you working on this still?

**Comment by Waishnav** [comment]
I would like to work on this issue.
Can you assign this to me

**Comment by Waishnav** [comment]
Just a small doubt, what is preferable toggle button or just icons which switched on click??
