### ISSUE TITLE
Use user avatar 

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#398]
![image](https://user-images.githubusercontent.com/19883954/186695749-8f8cce9b-3f4c-4785-8d6c-1490fe3c4697.png)

Use the user's avatar instead of the default paw logo when the user is logged in

**Comment by Lorenzo767** [comment]
Hi, just wanted to say that I will be working on this issue. 👍

**Comment by redxzeta** [comment]
> Hi, just wanted to say that I will be working on this issue. 👍

Are you still working on this?

**Comment by cody-castro** [comment]
I can work on this! :)

**Comment by bcastillo32** [comment]
Thanks @cody-castro !
