### ISSUE TITLE
Revamp the home page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#42]
Home page seems lacking. Maybe add featured pets of the week or random pets. 

Open to other features and feedback.

Feel free to remove the image and css if necessary

**Comment by agkosd** [comment]
I was hoping to contribute but I have an issue while running the project:

> Unable to Register for the Pet Finder API due to region Restrictions

**Comment by redxzeta** [comment]
hmm ill try emailing you a key

**Comment by redxzeta** [comment]
lmk if u got it

**Comment by agkosd** [comment]
Got it!

**Comment by agkosd** [comment]
Made a pull request #44.
>Added Featured Pets: shows 3 cats/dogs.

**Comment by agkosd** [comment]
Made a pull request #44.
>Added Featured Pets: shows 3 cats/dogs.

Let me know of any changes.
