### ISSUE TITLE
fix the icons from heroicons to use v2

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#428]
upgrading to heroicons v2

https://heroicons.com/

If the icon is not there, u can just use the svg file

**Comment by piyush-panpaliya** [comment]
Can I do this?
You want to migrate all icons to heroicons v2 and use svg if there isnt any equivalnt

**Comment by redxzeta** [comment]
> Can I do this? You want to migrate all icons to heroicons v2 and use svg if there isnt any equivalnt

Yeup

**Comment by piyush-panpaliya** [comment]
@redxzeta  should **react-icons** also be replaced?

**Comment by redxzeta** [comment]
> @redxzeta should **react-icons** also be replaced?

Probably not unless ur able to find the icon to replace with
