### ISSUE TITLE
Filter method for user favorited pets 

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#429]
Add filter method and sort method for user favorited pets

**Comment by Shivashish-rwt** [comment]
I would like to contribute. Can u please explain more where should i add those methods.?

**Comment by redxzeta** [comment]
you can add it in `Favorites.tsx`

**Comment by Shivashish-rwt** [comment]
Please assign this to me.

**Comment by Waishnav** [comment]
Hey could you assign this issue to me??

**Comment by redxzeta** [comment]
> hey @redxzeta, can you elaborate a little bit more ??

Filter user favorited pets based on breed or sort alpha on name

**Comment by Waishnav** [comment]
@redxzeta sorry for completing this issue late. 
#497 PR has solved this issue.
