### ISSUE TITLE
Organization Cards are not even

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#430]
![image](https://user-images.githubusercontent.com/19883954/193070965-0790857b-dde5-4cef-bd41-33fcdbe4ed1a.png)

make sure the cards are even in mobile and desktop

**Comment by ankitdas09** [comment]
do you want the height of the cards to be equal?

**Comment by redxzeta** [comment]
Yea

**Comment by vancassa** [comment]
May I work on this issue?

**Comment by cody-castro** [comment]
I'm working on this, could I be assigned?

**Comment by redxzeta** [comment]
> I'm working on this, could I be assigned?

Apologies, issues are first come first serve. There are other issues available. Let me know if u need help
