### ISSUE TITLE
Add a placeholder button while fetching in home page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#432]
![image](https://user-images.githubusercontent.com/19883954/193072875-35a79bf1-7440-4155-a839-c780429cbed6.png)

![image](https://user-images.githubusercontent.com/19883954/193073034-f0b66ce6-4503-4e6a-81e6-9633f2877959.png)

**Comment by omthakare16** [comment]
Hello
Can you Clearify what exactly you need regarding placeholder ?

**Comment by redxzeta** [comment]
Show the refresh button but change the text to a spinner and disable it until it loads

**Comment by omthakare16** [comment]
Hey, I have **resolved** this issue you can check **PR** #436 ,
Thanks for assigning me the work it was nice working on it .
