### ISSUE TITLE
Space out the buttons in resources page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#433]
![image](https://user-images.githubusercontent.com/19883954/193074436-cf71f951-1f21-4800-8475-366eeb47046a.png)

**Comment by Shivashish-rwt** [comment]
Can u please tell me where is the css of the reources page.?

**Comment by redxzeta** [comment]
> Can u please tell me where is the css of the reources page.?

Project uses tailwind

**Comment by omk-coder** [comment]
can i work on this issue.
