### ISSUE TITLE
UI Improvment in Resources Section

### ISSUE THREAD

**Issue by omthakare16** [redxzeta/Awesome-Adoption#450]
**Describe the bug**
Hey I saw their is some UI Improvement needed , in resources section their need gaps between the buttons , please check SS bellow
**Screenshot**
![Screenshot from 2022-10-03 17-08-08](https://user-images.githubusercontent.com/83799380/193569100-3fc51de0-27fc-44b5-b8e7-01ed43bd2e38.png)

Can I fix this issue !
Can you Assign me this work ?

**Comment by omthakare16** [comment]
Yes , I have seen their is settings issue in mobile view , but what about about page what's wrong with it ? Also Can you assign me for these all small bugs/issue . ?

**Comment by redxzeta** [comment]
Wanted to update the image and center it. Thinking to increase the results of the contributors since there's more now

**Comment by omthakare16** [comment]
So Can I work on these issues ?

**Comment by omthakare16** [comment]
Ok, can you also add the tag hacktoberfest in these issue,
as this would help me in this fest.

**Comment by omthakare16** [comment]
> Wanted to update the image and center it. Thinking to increase the results of the contributors since there's more now

Can you provide the image you wanted to replace in about page !
