### ISSUE TITLE
Add new Pet Types

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#451]
There are 3 pet types that have been added to the api : Small & Furry, Scales, Fins & Other, Barnyard

You can check them out using the api: https://api.petfinder.com/v2/types

- Add them to the `Pets.tsx` along with an image 
- Find an svg icon corresponding to the new type and add them in PetIcon
- Refactor and fix any tests

**Comment by siddhantprateek** [comment]
I would like to work on this issue, can u assign this to me?

**Comment by Potato-29** [comment]
Can I work on this
