### ISSUE TITLE
Footer always in the bottom

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#454]
Is it possible to place the footer in the bottom if the page is short? 

![image](https://user-images.githubusercontent.com/19883954/193973302-f878e4b4-6b3d-4d83-a8cf-c071c5eec485.png)

**Comment by heisdinesh** [comment]
can i work on this issue @redxzeta , do assign this issue to me

**Comment by viveena30** [comment]
can you assign this issue to me @redxzeta ?

**Comment by ranjankuldeep** [comment]
Is it still open?
Can i work on this. @redxzeta

**Comment by redxzeta** [comment]
> Is it still open? Can i work on this. @redxzeta

Sure
