### ISSUE TITLE
Mobile view login register page fix

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#459]
**Describe the bug**
Mobile view of sign in login form fields are over extending and the labels are touching

**To Reproduce**

Look in mobile view 

**Expected behavior**

**Screenshots**

![Screenshot_20221006-150729_Brave](https://user-images.githubusercontent.com/19883954/194427745-045de606-f3ee-4a52-a5a0-abec33838cf1.jpg)

**Comment by vanshika8750** [comment]
I can fix the label touch. If i can proceed then please assign me.

**Comment by hardikhans01** [comment]
Hi @redxzeta 
I want to work on this issue.
Could you please assign the task to me.
So please add a tag of Hacktoberfest 2022

**Comment by omthakare16** [comment]
Hey @redxzeta , 
I have already solved this issue for the login and settings page in PR #458  but unfortunately, My Bad I forget to make changes in register page.
You can assign anyone or me for this.

**Comment by omthakare16** [comment]
@redxzeta ,
Solved this minor issue in PR #463

**Comment by Naveen-Nair** [comment]
Hi @redxzeta, can i work on this issue?
