### ISSUE TITLE
Adding github link to footer

### ISSUE THREAD

**Issue by davidemmolino** [redxzeta/Awesome-Adoption#462]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Could get traction from people outside the intuit network

**Describe alternatives you've considered**

**Additional context**
We could add a url that leads to this github repo at the bottom of the page under the pages urls

**Comment by redxzeta** [comment]
Sounds like a good idea

**Comment by redxzeta** [comment]
Did u want to work on this ? @davidemmolino

**Comment by ranjankuldeep** [comment]
hey  I want to write add the description. I liked the idea, surely this will attract and give a customer a nice impression.

Please assign to me..

**Comment by davidemmolino** [comment]
@redxzeta yes, I would like to add this feature. thank you
