### ISSUE TITLE
Fix Forgot Password

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#466]
- Fix styling of forgot password.
- add validation for email 
- add a link to forgot password in the login sign up form

**Comment by Starboyzs** [comment]
I would like to work on this issue

**Comment by chinmaym07** [comment]
Hey @redxzeta . Can I work on this ?

**Comment by YuriDevAT** [comment]
Hi @redxzeta . I would like to work on this issue. :) 

Besides, I love your project. Did an Animal App like this too, to report abandoned dogs to the nearest NGO available. 💟 So I am happy to see other people care too.

**Comment by tab21** [comment]
Hey @redxzeta . Can I work on this issue?
