### ISSUE TITLE
Hide share action if browser does not support the WebShare APIs

### ISSUE THREAD

**Issue by foobar98** [redxzeta/Awesome-Adoption#467]
**Describe the bug**
If the browser does not support the WebShare API, the share CTA does nothing.

**To Reproduce**
Go to any animal page and click on share on a browser that does not have support for share.

**Expected behavior**
Share should not be shown in such scenarios.

**Comment by redxzeta** [comment]
Sounds like a good idea. Did u want to work on this ?

**Comment by foobar98** [comment]
> Sounds like a good idea. Did u want to work on this ?

Yeah, please assign it to me.
