### ISSUE TITLE
Fix ResetPassword page to use tailwind

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#479]
- convert the resetpassword component to use tailwind
-  uncomment the route in `App.tsx`

could be the same style as the register/login form

**Comment by stevenjburrows** [comment]
If you want to assign me I can help with this

**Comment by stevenjburrows** [comment]
are you also wanting react-bootstrap replaced?  As this is not in your package.json file

**Comment by redxzeta** [comment]
> are you also wanting react-bootstrap replaced? As this is not in your package.json file @redxzeta

Yea project uses tailwind daisyui
