### ISSUE TITLE
Dark mode testing

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#480]
Go through dark mode ui/ux and make a log of any issues or concerns.

Then post some issues that u found

**Comment by Eddayavuz** [comment]
Hey I'd like to work on this please. Could you assign me?

**Comment by xAtishayx** [comment]
#### Issues
1. Using dark mode logos (can use github dark logo)
<img width="1523" alt="image" src="https://user-images.githubusercontent.com/42544589/196461510-5739b57e-da88-49e5-a4bc-2b60c2a8854b.png">
2. Not readable filters (black or placeholder color can be used like in contact page)
<img width="602" alt="image" src="https://user-images.githubusercontent.com/42544589/196461996-f75e8c3e-0dcc-4487-a691-6c1e098fc6e7.png">

**Comment by redxzeta** [comment]
> ## Let me know below issues are viable or not so I can start working on them
> #### Issues
> 1. Using dark mode logos (can use github dark logo)
> 
> <img alt="image" width="1523" src="https://user-images.githubusercontent.com/42544589/196461510-5739b57e-da88-49e5-a4bc-2b60c2a8854b.png">
> 
> 2. Not readable filters (black or placeholder color can be used like in contact page)
> <img alt="image" width="602" src="https://user-images.githubusercontent.com/42544589/196461996-f75e8c3e-0dcc-4487-a691-6c1e098fc6e7.png">

Thanks for pointing out 
Feel free to make an issue
