### ISSUE TITLE
Image sizes in the carousel is not equal

### ISSUE THREAD

**Issue by Eddayavuz** [redxzeta/Awesome-Adoption#486]
**Describe the bug**
The cat image size in the carousel is not equal, some photos have oval corners some don't.

**To Reproduce**

1. Go to ['Cat Page'](https://pawternityhub.netlify.app/pets/cat)
2. Click on 'the number buttons on the carousel nav.' 
3. See the error

**Expected behavior**
All the photos should have equal size and equal style.

**Screenshots**
<img width="518" alt="Screen Shot 2022-10-12 at 11 17 36" src="https://user-images.githubusercontent.com/3321927/195300767-4eabc6af-5bac-4210-a635-e412be0b7db5.png">
<img width="513" alt="Screen Shot 2022-10-12 at 11 17 41" src="https://user-images.githubusercontent.com/3321927/195300780-b520eaaa-9210-487a-9a0e-0b7e8784dcbb.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 106.0.5249.119

**Additional context**
I can fix this issue. Please assign it to me.

**Comment by xAtishayx** [comment]
This issue had been for couple of days, I worked on it @redxzeta :) Please take a look #496

**Comment by jatinmark** [comment]
@redxzeta i want to work on this issue can you assign it to me
