### ISSUE TITLE
Incorrect discord link in "about" page

### ISSUE THREAD

**Issue by foobar98** [redxzeta/Awesome-Adoption#498]
**Describe the bug**
In the about page, both the "D" icon and the github icon has the same hyperlink.

**To Reproduce**

1. Go to about page.

**Expected behavior**
- If it's the discord icon
   - Use actual discord icon
   - Correct link to invite link

**Comment by redxzeta** [comment]
Good catch suppose to be a devpost link. U can add a discord link too

**Comment by foobar98** [comment]
Sure, can you assign it to me? I'll raise a PR.
