### ISSUE TITLE
Zipcode input flowing out of the container

### ISSUE THREAD

**Issue by foobar98** [redxzeta/Awesome-Adoption#499]
**Describe the bug**
In the pets page, when the window is resized to a smaller width, the zipcode input flows out of it's parent container.

**To Reproduce**

1. Go to `pets/birds` route.
2. Resize window.

**Expected behavior**
Input should not overflow on window resize.

**Screenshots**
<img width="441" alt="Screenshot 2022-10-20 at 6 01 51 PM" src="https://user-images.githubusercontent.com/25058106/196951403-aeb97df1-999f-483b-84c7-895fa7ea3601.png">

**Comment by redxzeta** [comment]
> **Describe the bug** In the pets page, when the window is resized to a smaller width, the zipcode input flows out of it's parent container.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to `pets/birds` route.
> 2. Resize window.
> 
> **Expected behavior** Input should not overflow on window resize.
> 
> **Screenshots** <img alt="Screenshot 2022-10-20 at 6 01 51 PM" width="441" src="https://user-images.githubusercontent.com/25058106/196951403-aeb97df1-999f-483b-84c7-895fa7ea3601.png">

Good catch did u want to fix this ?

**Comment by foobar98** [comment]
Yes, please assign it to me, thanks.
