### ISSUE TITLE
zipcode filter in one line instead of two in mobile version

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#50]
![image](https://user-images.githubusercontent.com/19883954/107994323-4b590b80-6f91-11eb-8d72-bbf5e526dc11.png)

zip code filter takes up two lines

**Comment by punndcoder28** [comment]
Hi @redxzeta . I would like to take this issue up, I was going through the code and I noticed you've used `width: "40%"` which is most likely causing the issue. I think changing this to a fixed width with horizontal padding show fix the issue or increasing `40%` to a higher value should do it. Do you have any suggestions on how this could be done better?

**Comment by redxzeta** [comment]
Maybe using media queries or min, max clamp. Feel free to experiment

**Comment by punndcoder28** [comment]
Sure! Will let you know how different things work out.

**Comment by punndcoder28** [comment]
Is this fine @redxzeta 
<img width="569" alt="Screenshot 2021-05-03 at 3 38 33 PM" src="https://user-images.githubusercontent.com/32433964/116864628-c98a8d00-ac25-11eb-994d-50776d286ac4.png">

**Comment by punndcoder28** [comment]
Is this fine @redxzeta 
<img width="569" alt="Screenshot 2021-05-03 at 3 38 33 PM" src="https://user-images.githubusercontent.com/32433964/116864702-e7f08880-ac25-11eb-8713-18f600924f02.png">
<img width="569" alt="Screenshot 2021-05-03 at 3 38 42 PM" src="https://user-images.githubusercontent.com/32433964/116864713-ecb53c80-ac25-11eb-932d-cd2c452bd2d8.png">
<img width="606" alt="Screenshot 2021-05-03 at 3 38 49 PM" src="https://user-images.githubusercontent.com/32433964/116864717-ee7f0000-ac25-11eb-9f24-0f539246fd37.png">
<img width="884" alt="Screenshot 2021-05-03 at 3 39 00 PM" src="https://user-images.githubusercontent.com/32433964/116864723-ef179680-ac25-11eb-863a-599e25288998.png">
<img width="1132" alt="Screenshot 2021-05-03 at 3 39 19 PM" src="https://user-images.githubusercontent.com/32433964/116864727-efb02d00-ac25-11eb-8631-3574f535e848.png">

**Comment by redxzeta** [comment]
yes looks great to me :)

**Comment by punndcoder28** [comment]
Will create a PR for this.
