### ISSUE TITLE
Set an explicit width and height on image elements to reduce layout shifts and improve CLS

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#51]

**Comment by punndcoder28** [comment]
Hi @redxzeta . Do you have a number in mind? I can take this up as well

**Comment by redxzeta** [comment]
Not atm. Maybe play around with so I can see the results

**Comment by punndcoder28** [comment]
I will update the same thread with results of different values and how they look.

**Comment by punndcoder28** [comment]
Hi @redxzeta . I've used `{ width: 300, height: 200}` for the images and this is the end result on different screens. Any suggestions would be great.
<img width="873" alt="Screenshot 2021-05-04 at 11 32 21 AM" src="https://user-images.githubusercontent.com/32433964/116965906-9ea74400-accc-11eb-9a24-77a12da0b563.png">
<img width="678" alt="Screenshot 2021-05-04 at 11 32 12 AM" src="https://user-images.githubusercontent.com/32433964/116965915-a535bb80-accc-11eb-932f-679fd3483cba.png">
<img width="671" alt="Screenshot 2021-05-04 at 11 32 04 AM" src="https://user-images.githubusercontent.com/32433964/116965918-a666e880-accc-11eb-97c7-132b15799d28.png">
<img width="691" alt="Screenshot 2021-05-04 at 11 31 56 AM" src="https://user-images.githubusercontent.com/32433964/116965920-a6ff7f00-accc-11eb-914e-ec88da16f125.png">
<img width="875" alt="Screenshot 2021-05-04 at 11 32 33 AM" src="https://user-images.githubusercontent.com/32433964/116965921-a7981580-accc-11eb-830f-3b527d816540.png">
<img width="1194" alt="Screenshot 2021-05-04 at 11 32 40 AM" src="https://user-images.githubusercontent.com/32433964/116965927-a830ac00-accc-11eb-9b83-129d6aee5b02.png">

**Comment by redxzeta** [comment]
could use some spacing underneath the card top border. maybe add padding-top 10px?
I am also curious to see what it looks like if the image 100% of the cards width

**Comment by punndcoder28** [comment]
These are images with 100% card width with padding at the top.
<img width="1156" alt="Screenshot 2021-05-07 at 5 15 41 PM" src="https://user-images.githubusercontent.com/32433964/117445308-2b196700-af58-11eb-9c64-43adc84e6c62.png">
<img width="920" alt="Screenshot 2021-05-07 at 5 15 29 PM" src="https://user-images.githubusercontent.com/32433964/117445331-310f4800-af58-11eb-93f6-67e5c825ff84.png">
<img width="911" alt="Screenshot 2021-05-07 at 5 15 19 PM" src="https://user-images.githubusercontent.com/32433964/117445337-32407500-af58-11eb-9942-f39083a887b8.png">
<img width="751" alt="Screenshot 2021-05-07 at 5 15 10 PM" src="https://user-images.githubusercontent.com/32433964/117445347-3371a200-af58-11eb-93d9-7186f90cfd53.png">
<img width="703" alt="Screenshot 2021-05-07 at 5 15 02 PM" src="https://user-images.githubusercontent.com/32433964/117445352-340a3880-af58-11eb-8b33-4d4f375c61ff.png">

**Comment by redxzeta** [comment]
Alright how about removing the padding top?
Any thoughts so far?

**Comment by punndcoder28** [comment]
Hi. Sorry for the late reply, yeah the top padding doesn't look good. It needs to go. I feel the `100%` is good but then we will have shifts in sizes for different screen sizes.

**Comment by redxzeta** [comment]
i think we can go with the first option just add the padding top

**Comment by punndcoder28** [comment]
@redxzeta Ok. I will go back to fixed width and height and add padding top. Will be creating a PR for this soon.

**Comment by punndcoder28** [comment]
Opened PR #54 for both issues
