### ISSUE TITLE
name of pet gets too long

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#55]
Some pet names get too long and extend the card height.
Maybe set a max number of characters for the pet name.
Open to suggestions.
![image](https://user-images.githubusercontent.com/19883954/119299794-81eb9580-bc14-11eb-9250-823450bcfbf3.png)

**Comment by SJellen** [comment]
<img width="1071" alt="Screen Shot 2021-05-24 at 2 35 35 PM" src="https://user-images.githubusercontent.com/51421669/119392206-7a240380-bc9d-11eb-8b53-99527766c0e9.png">

Also there is a need to replace some of the character codes with the correct characters. In this case the code is for ' .
The best bet would be to create a function that fixes the special characters and truncates the long names all in one. Then add that to every instance of the pet.name. like ....

```<h1>{petNameCleaner(pet.name)}</h1>```


I believe that there is also a css truncate option but it wouldn't fix the character code errors.
<img width="912" alt="Screen Shot 2021-05-24 at 2 50 00 PM" src="https://user-images.githubusercontent.com/51421669/119393762-5eb9f800-bc9f-11eb-9b06-7053d481673b.png">
[css truncate](https://daily-dev-tips.com/posts/css-truncate-text-with-ellipsis/)

**Comment by redxzeta** [comment]
oh thats a good point

**Comment by redxzeta** [comment]
did you want to create this issue or should I

**Comment by SJellen** [comment]
I'll give it a shot. At least I should have the function done quickly.  Look for a PR on Wednesday.

**Comment by SJellen** [comment]
I was going to add them together as a single js function. But if you prefer they can be broken into 2. 
A function for the regex and the  css fix for the truncating.

**Comment by redxzeta** [comment]
Ahh okay thats fine
