### ISSUE TITLE
Optmize the Resource page 

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#70]
Optimize the Resource page for best practices. Some of the code has `<br>` tags or uses `<b>` tags. Feel free to update the css and `Resources.js`

```
    <br />
        <br />
        <b>
          Pawternity Hub wants to help you stay safe and help you find a friend
          that can keep you company during the pandemic
          <br /> Check out the links below for more information about adoption
          during Covid-19
        </b>
        <br />
```

**Comment by Abhay2412** [comment]
Hi, I would like to give a shot at working on this

**Comment by Abhay2412** [comment]
Would you like me to just make a commit I think I have something ready for the Resources.js file I have used <p> tags instead of the br tags

**Comment by redxzeta** [comment]
Did your fork it?

**Comment by Abhay2412** [comment]
Will fork it and make a pull request

**Comment by redxzeta** [comment]
are you still working on it @Abhay2412

**Comment by Abhay2412** [comment]
You can have someone else on it thanks for the opportunity though

**Comment by MAZ12211** [comment]
Hey, @redxzeta I would like to work on this. I should be able to do this using `<p>` tags and **style** them with very little code.

**Comment by redxzeta** [comment]
Sure

**Comment by redxzeta** [comment]
@MAZ12211 apologies. It should be fixed now. It was because of eslint and prettier

**Comment by redxzeta** [comment]
Be sure to update with the latest change
