### ISSUE TITLE
Create a Login and Register Page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#75]
Create a page for user login and user register page could include email, username, password. 

If possible, add validation checks.

For the navigation bar, implement a drop down from `react-bootstrap`, and then add links to login and register. The title could be `Profile`

Planning to implement supabase to handle the data.

**Comment by AbhishekKakad12** [comment]
Hey! I am new  to open source, could you please assign this one to me?

**Comment by AbhishekKakad12** [comment]
Can I use material ui library to implement it ?

**Comment by redxzeta** [comment]
Would prefer to use `react-bootstrap` to not get confusing

[react-bootstrap docs](https://react-bootstrap.github.io/components/forms/)

**Comment by AbhishekKakad12** [comment]
OK

**Comment by AbhishekKakad12** [comment]
login and register page created , to push the code I have to create new branch or I can push the code in main branch?

**Comment by redxzeta** [comment]
make a pull request with your branch
