### ISSUE TITLE
Migrate to Bootstrap 5

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#79]
Migrate to Bootstrap 5 [docs](https://react-bootstrap.github.io/getting-started/introduction/)

```
    "react-bootstrap": "^1.6.0",
    "bootstrap": "^4.5.3",
    "bootswatch": "^4.5.2",
```

these need updating

There might be some breaking changes and may need to update the code

**Comment by emraftis** [comment]
Hey @redxzeta! I just cloned the repo and I'll try working through updating Bootstrap to 5.1.0!
