### ISSUE TITLE
Adding border to contributors

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#84]
In the contributors page, some of them have a white background blending it in.

Add a black border around it or variety of colors

**Comment by MAZ12211** [comment]
Hello. Assign me this issue.

**Comment by harishfalco** [comment]
Hello redxzeta , I am looking forward to work on this please assign it to me

**Comment by redxzeta** [comment]
Be sure to create a pull request in October for Hactoberfest
