### ISSUE TITLE
Add title and onHover effect on Pets.js

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#86]
There isn't a title for each picture.

Add an onhover effect over each image which shows the text for the type of pet 
add onhover effect color over it something like this below. Feel free to experiment and variety of colors

![image](https://user-images.githubusercontent.com/19883954/135137855-6dbb8ba5-0b32-4c14-b3d3-2b9f30bc76a0.png)

**Comment by rajdama** [comment]
I can do it.

**Comment by redxzeta** [comment]
Sure. Be sure to create a pr on October for hactoberfest :)

**Comment by rajdama** [comment]
Okay : )

**Comment by rajdama** [comment]
@redxzeta  I had made the pull request.
