### ISSUE TITLE
Add a 404 page

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#88]
Add a 404 page when a user tries to enter a page that does not exist

and add an image of pets or something

put a button that helps users redirect to the home page, button redirect to  `/about` , and button for `/pets`

**Comment by tuanthanh2067** [comment]
Hello there, I'm interested in your project and wanted to work on this issue. Can you

**Comment by tuanthanh2067** [comment]
Hello there, I found this project quite interesting and wanted to contribute. Can you please assign me to this issue?

**Comment by redxzeta** [comment]
Sure. are you participating in hactoberfest? if yes, create a pull request in October

**Comment by tuanthanh2067** [comment]
I will. But I have a question, do we really need `/about` button and `/pets` button in the 404 page because users can use the navigation bar to redirect?

**Comment by redxzeta** [comment]
Oh that's true. I guess u don't have to put it then
