### ISSUE TITLE
New Logo for the site

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#89]
Anyone want to create a new logo for the site?

Replace PawHub in the Navigation bar with the logo

Add the logo to the site

**Comment by nirajacharyaa** [comment]
Hey, I would like to give a logo to it.
![image](https://user-images.githubusercontent.com/54741119/135487184-cccff2f1-f517-424d-98ae-c71dbb08a660.png)
Is this logo fine?

**Comment by yashika2406** [comment]
I have solved this issue
PR link:
https://github.com/redxzeta/Awesome-Adoption/pull/91
kindly merge

**Comment by PrajaktaSathe** [comment]
I can try!

**Comment by PrajaktaSathe** [comment]
I've created a new logo for this project! But, I'm a complete beginner to React and don't want to mess things up😅. So, could you tell me in which folder/where should I add the logo?
Thanks!

**Comment by redxzeta** [comment]
you could put it in `src/components/layout`

and then open the file `NavigationBar.js`


then at the top have something like `import Logo from './imgname.ext'`

Create a pull request so i can help u out too :)

**Comment by PrajaktaSathe** [comment]
I have opened up a PR #94
Please let me know if it looks good!
Thank you!
