### ISSUE TITLE
Add Divider in NavigationBar

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#96]
Add `<NavDropdown.Divider />` in the dropdown in the NavigationBar to separate All Pets

**Comment by zivkaziv** [comment]
I'll be happy to take this as well

**Comment by zivkaziv** [comment]
<img width="429" alt="Screen Shot 2021-10-05 at 23 26 54" src="https://user-images.githubusercontent.com/9402714/136097612-226fde66-c2a5-4a09-8182-232adb40e3e7.png">
Do we want the divider here? 
Or between each animal? Dog | Cat...?
