### ISSUE TITLE
Replace links with img in about page 

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#98]
replace with image  ie youtube image for youtube link 

![image](https://user-images.githubusercontent.com/19883954/136092173-db1a93ac-0eb7-46a4-ad53-662cde349b6d.png)

**Comment by juanmaotegui** [comment]
Can I work on this?

**Comment by juanmaotegui** [comment]
I created the #101  for this issue. Can you review it? Thanks!
